<?php

/*
 * Create table for URN:NBN reservations
 */
function urn_nbn_registrator_schema() {
  $schema['urn_nbn_registrator_reservations'] = array(
    'description' => 'Table for URN:NBN reservations',
    'fields' => array(
      'id' => array(
        'description' => 'URN:NBN', 
        'type' => 'varchar', 
        'length' => 32,
        'not null' => TRUE
      ), 
    ),
    'primary key' => array('id')
  );
  return $schema;
}

?>